### ISSUE TITLE
(Lyrics question)

### ISSUE THREAD

**Issue by ZaboT1** [SyndiShanX/Spotify-Dark#2]
Hi developers, I used your theme and I like it clean and simple!
Lengthening parts of the picture and shrinking words are a hundred times better than the original, making it easy to read and comfortable

But the question I want to ask in return is.
When the lyrics are too long, they don't auto-homing, they show up in their entirety.
Is it possible to develop a mode to manually select all lyrics to display, or to auto-guide lyrics?

![Snipaste_2022-02-25_14-17-55](https://user-images.githubusercontent.com/71028992/155664610-1cd160ca-c3bb-43d9-93cd-5f80a06a8b5b.png)
![Snipaste_2022-02-25_14-18-17](https://user-images.githubusercontent.com/71028992/155664640-98f850fc-a7c0-4cef-ba3c-3676d217b377.png)

Picture 1(full open)
Picture 2 (refers to dynamic lyrics)

**Comment by SyndiShanX** [comment]
The Lyrics weren't synced to the song either by Spotify or the Songs Artist, I can't fix this issue with a theme, sorry
