### ISSUE TITLE
wierd box near close and minimise boxes

### ISSUE THREAD

**Issue by Goten87** [SyndiShanX/Spotify-Dark#5]
Hello at the right top where the close - full screen and minimise is i have a wierd box thats a other color

running latest Spotify and addon as well
OS: Win10

![image](https://github.com/SyndiShanX/Spotify-Dark/assets/1938598/08772ebc-1fc9-4e74-bd75-964477d004c8)

**Comment by SyndiShanX** [comment]
The only fix would be to remove the brightness filter that makes it match the background
![image](https://github.com/SyndiShanX/Spotify-Dark/assets/23367120/a2841d33-b7eb-4d08-863b-6789f197a70f)

**Comment by SyndiShanX** [comment]
Should be Fixed whenever Spicetify Fetches the new Commit, Thanks for Reporting
