### ISSUE TITLE
update broke theme compleetly i think

### ISSUE THREAD

**Issue by Goten87** [SyndiShanX/Spotify-Dark#8]
just got a update and now the  theme is broken and needs a big update i think please check this ^^ thank you

**Comment by SyndiShanX** [comment]
Seems fine for me on Stable and Canary, reopen this if you Reinstall BetterDiscord and it's still a problem

**Comment by Goten87** [comment]
Well reopen right away sins its not BetterDiscord but for Spotify?

**Comment by SyndiShanX** [comment]
Oh my bad, I misread the repo, I’ll look into it tomorrow

**Comment by SyndiShanX** [comment]
Seems fine for me, even on the latest version, is your Spotify and Spicetify up to date?
